In [4]:
import numpy as np
import pandas as pd

data = pd.read_csv('food_wastage_data.csv')
data

,Type of Food,Number of Guests,Event Type,Quantity of Food,Storage Conditions,Purchase History,Seasonality,Preparation Method,Geographical Location,Pricing,Wastage Food Amount
0,Meat,310,Corporate,450,Refrigerated,Regular,All Seasons,Buffet,Urban,Low,25
1,Meat,400,Birthday,500,Room Temperature,Regular,Winter,Buffet,Suburban,High,40
2,Vegetables,302,Birthday,371,Refrigerated,Regular,Summer,Buffet,Suburban,Low,27
3,Meat,491,Birthday,497,Refrigerated,Regular,All Seasons,Finger Food,Rural,High,32
4,Meat,300,Corporate,400,Refrigerated,Regular,Winter,Finger Food,Urban,Moderate,25
...,...,...,...,...,...,...,...,...,...,...,...
1777,Baked Goods,310,Corporate,350,Room Temperature,Regular,Summer,Finger Food,Urban,High,35
1778,Baked Goods,284,Social Gathering,443,Room Temperature,Regular,Winter,Buffet,Rural,Low,32
1779,Fruits,220,Wedding,300,Room Temperature,Regular,All Seasons,Finger Food,Urban,Moderate,15
1780,Fruits,250,Wedding,350,Room Temperature,Regular,All Seasons,Finger Food,Rural,Moderate,20
1781,Baked Goods,400,Wedding,500,Room Temperature,Regular,Winter,Sit-down Dinner,Rural,High,45

In [5]:
data.isnull().sum()

Type of Food              0
Number of Guests          0
Event Type                0
Quantity of Food          0
Storage Conditions        0
Purchase History          0
Seasonality               0
Preparation Method        0
Geographical Location     0
Pricing                   0
Wastage Food Amount       0
dtype: int64

In [6]:
mappings = {}

for column in data.select_dtypes(include=['object']).columns:
    data[column] = data[column].astype('category')
    mappings[column] = dict(enumerate(data[column].cat.categories))
    data[column] = data[column].cat.codes

print(data.head())
print("\nMappings:\n")
for column, mapping in mappings.items():
    print(f"{column}: {mapping}")

   Type of Food     Number of Guests   Event Type         Quantity of Food   \
0                3                310                  1                450
1                3                400                  0                500
2                4                302                  0                371
3                3                491                  0                497
4                3                300                  1                400

   Storage Conditions   Purchase History   Seasonality   Preparation Method   \
0                    0                  1             0                    0
1                    1                  1             2                    0
2                    0                  1             1                    0
3                    0                  1             0                    1
4                    0                  1             2                    1

   Geographical Location   Pricing    Wastage Food Amount
0                       2          1                   25
1                       1          0                   40
2                       1          1                   27
3                       0          0                   32
4                       2          2                   25

Mappings:

Type of Food   : {0: 'Baked Goods    ', 1: 'Dairy Products ', 2: 'Fruits         ', 3: 'Meat           ', 4: 'Vegetables     '}
Event Type       : {0: 'Birthday         ', 1: 'Corporate        ', 2: 'Social Gathering ', 3: 'Wedding          '}
Storage Conditions : {0: 'Refrigerated       ', 1: 'Room Temperature   '}
Purchase History : {0: 'Occasional       ', 1: 'Regular          '}
Seasonality : {0: 'All Seasons ', 1: 'Summer      ', 2: 'Winter      '}
Preparation Method : {0: 'Buffet             ', 1: 'Finger Food        ', 2: 'Sit-down Dinner    '}
Geographical Location : {0: 'Rural                 ', 1: 'Suburban              ', 2: 'Urban                 '}
Pricing  : {0: 'High     ', 1: 'Low      ', 2: 'Moderate '}

In [7]:
data.shape

(1782, 11)

In [8]:
data.describe()

,Type of Food,Number of Guests,Event Type,Quantity of Food,Storage Conditions,Purchase History,Seasonality,Preparation Method,Geographical Location,Pricing,Wastage Food Amount
count,1782.000000,1782.000000,1782.000000,1782.000000,1782.000000,1782.000000,1782.000000,1782.000000,1782.000000,1782.000000,1782.000000
mean,1.794613,317.804714,1.543771,411.125701,0.649270,0.884400,1.005051,1.270483,1.093715,0.999439,28.536476
std,1.354765,67.829658,1.073933,65.204674,0.477332,0.319835,0.839425,0.730205,0.728558,0.869665,10.461317
min,0.000000,207.000000,0.000000,280.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,10.000000
25%,1.000000,267.000000,1.000000,350.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,20.000000
50%,2.000000,302.000000,2.000000,400.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,26.500000
75%,3.000000,350.000000,2.000000,480.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,35.000000
max,4.000000,491.000000,3.000000,500.000000,1.000000,1.000000,2.000000,2.000000,2.000000,2.000000,63.000000

In [9]:
data.corr()

,Type of Food,Number of Guests,Event Type,Quantity of Food,Storage Conditions,Purchase History,Seasonality,Preparation Method,Geographical Location,Pricing,Wastage Food Amount
Type of Food,1.000000,-0.027829,0.015059,-0.006528,-0.688851,-0.189592,0.172731,0.016458,0.012117,-0.004387,-0.013892
Number of Guests,-0.027829,1.000000,-0.003760,0.794401,-0.006053,0.009544,-0.006491,0.143111,0.068440,-0.406790,0.650421
Event Type,0.015059,-0.003760,1.000000,0.024353,-0.034111,-0.076802,0.026225,0.157450,-0.040050,-0.033339,0.030344
Quantity of Food,-0.006528,0.794401,0.024353,1.000000,-0.047273,-0.011688,-0.005613,0.220788,0.125557,-0.409757,0.638648
Storage Conditions,-0.688851,-0.006053,-0.034111,-0.047273,1.000000,0.260204,-0.102076,-0.048244,-0.015222,0.018462,-0.029876
Purchase History,-0.189592,0.009544,-0.076802,-0.011688,0.260204,1.000000,-0.052199,0.035388,0.085072,-0.034550,0.026936
Seasonality,0.172731,-0.006491,0.026225,-0.005613,-0.102076,-0.052199,1.000000,0.061892,0.014833,-0.014610,0.016124
Preparation Method,0.016458,0.143111,0.157450,0.220788,-0.048244,0.035388,0.061892,1.000000,0.152856,-0.115588,0.237519
Geographical Location,0.012117,0.068440,-0.040050,0.125557,-0.015222,0.085072,0.014833,0.152856,1.000000,-0.027388,0.085928
Pricing,-0.004387,-0.406790,-0.033339,-0.409757,0.018462,-0.034550,-0.014610,-0.115588,-0.027388,1.000000,-0.685755
Wastage Food Amount,-0.013892,0.650421,0.030344,0.638648,-0.029876,0.026936,0.016124,0.237519,0.085928,-0.685755,1.000000

In [10]:
data.corr()['Wastage Food Amount']

Type of Food             -0.013892
Number of Guests          0.650421
Event Type                0.030344
Quantity of Food          0.638648
Storage Conditions       -0.029876
Purchase History          0.026936
Seasonality               0.016124
Preparation Method        0.237519
Geographical Location     0.085928
Pricing                  -0.685755
Wastage Food Amount       1.000000
Name: Wastage Food Amount, dtype: float64

In [11]:
x = data.drop('Wastage Food Amount', axis=1)
y = data['Wastage Food Amount']

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(1425, 10) (357, 10) (1425,) (357,)

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR


regressors = [
    make_pipeline(StandardScaler(), LinearRegression()),
    make_pipeline(StandardScaler(), Ridge()),
    make_pipeline(StandardScaler(), Lasso()),
    make_pipeline(StandardScaler(), DecisionTreeRegressor()),
    make_pipeline(StandardScaler(), RandomForestRegressor()),
    make_pipeline(StandardScaler(), GradientBoostingRegressor()),
    make_pipeline(StandardScaler(), SVR())
]


best_mse = float('inf')
best_r2 = 0
best_regressor = None
for regressor in regressors:
    regressor.fit(x_train, y_train)
    predictions = regressor.predict(x_test)
    mse = mean_squared_error(y_test, predictions)
    r2 = r2_score(y_test, predictions)
    if mse < best_mse:
        best_mse = mse
        best_regressor = regressor
        best_r2 = r2


print(f"Best Regressor: {best_regressor}")
print(f"Best MSE: {best_mse}")
print(f"Best R2: {best_r2}")

Best Regressor: Pipeline(steps=[('standardscaler', StandardScaler()),
                ('randomforestregressor', RandomForestRegressor())])
Best MSE: 7.217720249434033
Best R2: 0.930369728378787

In [34]:
import pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(best_regressor, file)

In [40]:
a = best_regressor.predict([[1,2,3,4,1,2,3,4,2,3]])
print(a)

[22.1]

C:\Users\gsuma\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(